service: lambda-s3-client
plugins:
  - serverless-ignore
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: true
functions:
  handler:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: dist/handler.handler # highlight-line
    events:
      - httpApi: '*'
